name: build

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      py_version:
        required: true
        type: string
        default: "3.14"
      compile_os:
        required: true
        type: string
        default: "['ubuntu-latest', 'ubuntu-24.04-arm', 'windows-latest', 'windows-11-arm', 'macos-15-intel', 'macos-14']"

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.compile_os) }}

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        
      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          retention-days: 1

  build_sdist_and_upload:
    name: Build tar.gz and upload
    runs-on: ubuntu-latest
    needs: build_wheels

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.py_version }}

      - run: pip install build -U
      - run: python -m build -s

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./dist/
          merge-multiple: true

      - name: Add file to release
        uses: cssnr/upload-release-action@v1
        with:
          globs: |
            ./dist/*.whl
            ./dist/*.tar.gz

      - id: repo-basename
        run: echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload files to server
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          localDir: ./dist/
          remoteDir: ${{ secrets.UPLOAD_DIR }}/${{ steps.repo-basename.outputs.value }}/${{ inputs.tag_name }}_${{ github.run_id }}_${{ github.run_attempt }}
          forceUpload: true
